# Generated by Django 5.0.7 on 2024-08-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('subcateggory', models.CharField(max_length=255, null=True)),
                ('brand', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=15, null=True)),
                ('price', models.FloatField()),
                ('cost', models.FloatField()),
                ('stockQuantity', models.IntegerField()),
                ('reorderLevel', models.IntegerField()),
                ('productImages', models.ImageField(upload_to='products/')),
                ('qr', models.ImageField(blank=True, null=True, upload_to='qr_code/')),
                ('tags', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StoreManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
